import type { Order } from "@/types";

export const mockOrders: Order[] = [
  // ── Order 1: Confirmed ────────────────────────────────────────────────────
  {
    id: "ord-001",
    userId: "user-me",
    orderNumber: "UP-2025-00847",
    status: "confirmed",
    statusHistory: [
      { status: "placed", timestamp: "2026-04-23T10:30:00Z", note: "Order received and payment confirmed." },
      { status: "confirmed", timestamp: "2026-04-23T11:15:00Z", note: "Artwork reviewed and approved. Queued for print." },
    ],
    items: [
      {
        productId: "prod-bc-1",
        productName: "Standard Business Cards",
        productSlug: "standard-business-cards",
        productImage: "https://picsum.photos/seed/bc1a/800/600",
        config: {
          sizeId: "sz-std",
          sizeLabel: 'Standard (3.5" × 2")',
          paperId: "pp-16pt",
          paperLabel: "16pt Cardstock",
          finishId: "fn-matte",
          finishLabel: "Matte",
          sides: "double",
          quantity: 250,
          turnaroundId: "to-standard",
          turnaroundLabel: "Standard (5–7 business days)",
          artworkFileName: "business_card_v3.pdf",
          artworkFileSize: 2457600,
        },
        pricePerUnit: 3.20,
        totalPrice: 800.00,
      },
    ],
    shippingAddress: {
      label: "Home",
      fullName: "Arjun Sharma",
      line1: "42, Linking Road",
      line2: "Bandra West",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400050",
      country: "India",
    },
    subtotal: 800.00,
    shippingCost: 99.00,
    taxAmount: 162.00,
    totalAmount: 1061.00,
    paymentMethod: "UPI — arjun@okaxis",
    placedAt: "2026-04-23T10:30:00Z",
    updatedAt: "2026-04-23T11:15:00Z",
  },

  // ── Order 2: Actively Printing ────────────────────────────────────────────
  {
    id: "ord-002",
    userId: "user-me",
    orderNumber: "UP-2025-00791",
    status: "printing",
    statusHistory: [
      { status: "placed", timestamp: "2026-04-18T14:00:00Z", note: "Order received and payment confirmed." },
      { status: "confirmed", timestamp: "2026-04-18T14:45:00Z", note: "Artwork approved. Scheduled for print run." },
      { status: "printing", timestamp: "2026-04-20T08:00:00Z", note: "Your order is currently on the press." },
    ],
    items: [
      {
        productId: "prod-fl-1",
        productName: "A5 Promotional Flyers",
        productSlug: "a5-promotional-flyers",
        productImage: "https://picsum.photos/seed/fl1a/800/600",
        config: {
          sizeId: "sz-a5",
          sizeLabel: 'A5 (5.83" × 8.27")',
          paperId: "pp-130gsm",
          paperLabel: "130gsm Silk",
          finishId: "fn-gloss",
          finishLabel: "Gloss Laminate",
          sides: "double",
          quantity: 1000,
          turnaroundId: "to-standard",
          turnaroundLabel: "Standard (5–7 business days)",
          artworkFileName: "summer_sale_flyer.pdf",
          artworkFileSize: 5242880,
        },
        pricePerUnit: 1.50,
        totalPrice: 1500.00,
      },
      {
        productId: "prod-br-1",
        productName: "A4 Tri-Fold Brochure",
        productSlug: "a4-tri-fold-brochure",
        productImage: "https://picsum.photos/seed/br1a/800/600",
        config: {
          sizeId: "sz-a4-tri",
          sizeLabel: 'A4 Tri-Fold (8.27" × 11.69")',
          paperId: "pp-170gsm",
          paperLabel: "170gsm Silk",
          finishId: "fn-matte",
          finishLabel: "Matte Laminate",
          sides: "double",
          quantity: 250,
          turnaroundId: "to-standard",
          turnaroundLabel: "Standard (5–7 business days)",
          artworkFileName: "company_brochure_final.pdf",
          artworkFileSize: 8388608,
        },
        pricePerUnit: 4.92,
        totalPrice: 1230.00,
      },
    ],
    shippingAddress: {
      label: "Office",
      fullName: "Arjun Sharma",
      line1: "15, Brigade Road",
      line2: "3rd Floor, Tech Hub",
      city: "Bengaluru",
      state: "Karnataka",
      postalCode: "560001",
      country: "India",
    },
    subtotal: 2730.00,
    shippingCost: 0.00,
    taxAmount: 491.40,
    totalAmount: 3221.40,
    paymentMethod: "HDFC Visa ending 4242",
    estimatedDelivery: "2026-04-27",
    placedAt: "2026-04-18T14:00:00Z",
    updatedAt: "2026-04-20T08:00:00Z",
  },

  // ── Order 3: Delivered with tracking ─────────────────────────────────────
  {
    id: "ord-003",
    userId: "user-me",
    orderNumber: "UP-2025-00734",
    status: "delivered",
    statusHistory: [
      { status: "placed", timestamp: "2026-04-08T09:00:00Z", note: "Order received and payment confirmed." },
      { status: "confirmed", timestamp: "2026-04-08T09:30:00Z", note: "Artwork approved. Queued for print." },
      { status: "printing", timestamp: "2026-04-09T07:45:00Z", note: "Your order is on the press." },
      { status: "shipped", timestamp: "2026-04-11T15:00:00Z", note: "Dispatched via Delhivery Express." },
      { status: "delivered", timestamp: "2026-04-13T11:20:00Z", note: "Delivered to your address. Enjoy your prints!" },
    ],
    items: [
      {
        productId: "prod-bc-2",
        productName: "Luxury Foil Business Cards",
        productSlug: "luxury-foil-business-cards",
        productImage: "https://picsum.photos/seed/bc2a/800/600",
        config: {
          sizeId: "sz-std",
          sizeLabel: 'Standard (3.5" × 2")',
          paperId: "pp-32pt",
          paperLabel: "32pt Ultra Thick",
          finishId: "fn-foil",
          finishLabel: "Foil Stamp",
          sides: "double",
          quantity: 100,
          turnaroundId: "to-rush",
          turnaroundLabel: "Rush (3 business days)",
          artworkFileName: "foil_card_gold.ai",
          artworkFileSize: 15728640,
        },
        pricePerUnit: 12.60,
        totalPrice: 1260.00,
      },
      {
        productId: "prod-bn-1",
        productName: "Vinyl Outdoor Banner",
        productSlug: "vinyl-outdoor-banner",
        productImage: "https://picsum.photos/seed/bn1a/800/600",
        config: {
          sizeId: "sz-3x6",
          sizeLabel: "3ft × 6ft",
          paperId: "pp-13oz",
          paperLabel: "13oz Vinyl",
          finishId: "fn-gloss",
          finishLabel: "Gloss",
          sides: "single",
          quantity: 2,
          turnaroundId: "to-rush",
          turnaroundLabel: "Rush (3 business days)",
          artworkFileName: "event_banner_3x6.pdf",
          artworkFileSize: 20971520,
        },
        pricePerUnit: 472.50,
        totalPrice: 945.00,
      },
    ],
    shippingAddress: {
      label: "Home",
      fullName: "Arjun Sharma",
      line1: "42, Linking Road",
      line2: "Bandra West",
      city: "Mumbai",
      state: "Maharashtra",
      postalCode: "400050",
      country: "India",
    },
    subtotal: 2205.00,
    shippingCost: 149.00,
    taxAmount: 430.08,
    totalAmount: 2784.08,
    paymentMethod: "UPI — arjun@okaxis",
    trackingNumber: "DLVY748291635IN",
    estimatedDelivery: "2026-04-13",
    placedAt: "2026-04-08T09:00:00Z",
    updatedAt: "2026-04-13T11:20:00Z",
  },
];
