import type { Product, PricingTier, TurnaroundOption, PrintSpec, SidesOption, TemplateField, CustomizationMode } from "@/types";

// ─── Shared turnaround options ────────────────────────────────────────────────

const standardTurnaround: TurnaroundOption[] = [
  { id: "to-standard", label: "Standard (5–7 business days)", businessDays: 7, extraCost: 0 },
  { id: "to-rush", label: "Rush (3 business days)", businessDays: 3, extraCost: 200 },
  { id: "to-overnight", label: "Overnight (next business day)", businessDays: 1, extraCost: 500 },
];

// ─── Pricing tier helpers ─────────────────────────────────────────────────────

function makeTiers(base: number, quantities: number[]): PricingTier[] {
  const discounts = [0, 0.10, 0.18, 0.25, 0.32, 0.38];
  return quantities.map((qty, i) => {
    const pu = parseFloat((base * (1 - (discounts[i] ?? discounts[discounts.length - 1]))).toFixed(2));
    return {
      quantity: qty,
      pricePerUnit: pu,
      totalPrice: parseFloat((pu * qty).toFixed(2)),
      isBestValue: i === Math.floor(quantities.length / 2),
    };
  });
}

// ─── Shared print specs ───────────────────────────────────────────────────────

const SIDES_SINGLE: SidesOption = { label: "Single", priceMultiplier: 1, isDefault: true };
const SIDES_DOUBLE: SidesOption = { label: "Double", priceMultiplier: 1.5, isDefault: false };

const businessCardSpec: PrintSpec = {
  sizes: [
    { id: "sz-std", label: 'Standard (3.5" × 2")', width: 3.5, height: 2, unit: "in", priceMultiplier: 1, isDefault: true },
    { id: "sz-sq", label: 'Square (2.5" × 2.5")', width: 2.5, height: 2.5, unit: "in", priceMultiplier: 1.05, isDefault: false },
    { id: "sz-eu", label: 'European (3.35" × 2.17")', width: 3.35, height: 2.17, unit: "in", priceMultiplier: 1, isDefault: false },
  ],
  papers: [
    { id: "pp-14pt", label: "14pt Cardstock", weight: "14pt", description: "Standard thick card stock", priceMultiplier: 1, isDefault: true },
    { id: "pp-16pt", label: "16pt Cardstock", weight: "16pt", description: "Premium thick, great rigidity", priceMultiplier: 1.15, isDefault: false },
    { id: "pp-32pt", label: "32pt Ultra Thick", weight: "32pt", description: "Luxuriously thick, premium feel", priceMultiplier: 1.4, isDefault: false },
  ],
  finishes: [
    { id: "fn-matte", label: "Matte", description: "Soft, non-reflective finish", priceMultiplier: 1, isDefault: true },
    { id: "fn-gloss", label: "Gloss", description: "Shiny, vibrant colors", priceMultiplier: 1, isDefault: false },
    { id: "fn-uv", label: "Spot UV", description: "Glossy highlights on matte base", priceMultiplier: 1.3, isDefault: false },
    { id: "fn-foil", label: "Foil Stamp", description: "Metallic foil accents", priceMultiplier: 1.5, isDefault: false },
  ],
  sides: [SIDES_SINGLE, SIDES_DOUBLE],
  minDpi: 300,
  bleedMm: 3,
};

const flyerSpec: PrintSpec = {
  sizes: [
    { id: "sz-a5", label: 'A5 (5.83" × 8.27")', width: 5.83, height: 8.27, unit: "in", priceMultiplier: 1, isDefault: true },
    { id: "sz-a4", label: 'A4 (8.27" × 11.69")', width: 8.27, height: 11.69, unit: "in", priceMultiplier: 1.3, isDefault: false },
    { id: "sz-dl", label: 'DL (3.9" × 8.27")', width: 3.9, height: 8.27, unit: "in", priceMultiplier: 0.9, isDefault: false },
  ],
  papers: [
    { id: "pp-100gsm", label: "100gsm Silk", weight: "100gsm", description: "Standard quality, semi-gloss", priceMultiplier: 1, isDefault: true },
    { id: "pp-130gsm", label: "130gsm Silk", weight: "130gsm", description: "Mid-weight, vibrant print", priceMultiplier: 1.15, isDefault: false },
    { id: "pp-170gsm", label: "170gsm Silk", weight: "170gsm", description: "Heavier, more premium feel", priceMultiplier: 1.3, isDefault: false },
  ],
  finishes: [
    { id: "fn-matte", label: "Matte Laminate", description: "Soft, elegant, anti-glare", priceMultiplier: 1.1, isDefault: true },
    { id: "fn-gloss", label: "Gloss Laminate", description: "Shiny, bright, eye-catching", priceMultiplier: 1.1, isDefault: false },
    { id: "fn-uncoated", label: "Uncoated", description: "Natural paper feel, writable", priceMultiplier: 1, isDefault: false },
  ],
  sides: [SIDES_SINGLE, SIDES_DOUBLE],
  minDpi: 300,
  bleedMm: 3,
};

const bannerSpec: PrintSpec = {
  sizes: [
    { id: "sz-2x4", label: "2ft × 4ft", width: 24, height: 48, unit: "in", priceMultiplier: 1, isDefault: true },
    { id: "sz-3x6", label: "3ft × 6ft", width: 36, height: 72, unit: "in", priceMultiplier: 1.8, isDefault: false },
    { id: "sz-4x8", label: "4ft × 8ft", width: 48, height: 96, unit: "in", priceMultiplier: 2.5, isDefault: false },
    { id: "sz-5x10", label: "5ft × 10ft", width: 60, height: 120, unit: "in", priceMultiplier: 3.5, isDefault: false },
  ],
  papers: [
    { id: "pp-13oz", label: "13oz Vinyl", weight: "13oz", description: "Standard indoor/outdoor vinyl", priceMultiplier: 1, isDefault: true },
    { id: "pp-18oz", label: "18oz Heavy Vinyl", weight: "18oz", description: "Heavy-duty, wind-resistant", priceMultiplier: 1.25, isDefault: false },
    { id: "pp-fabric", label: "Polyester Fabric", weight: "fabric", description: "Wrinkle-resistant, elegant", priceMultiplier: 1.4, isDefault: false },
  ],
  finishes: [
    { id: "fn-matte", label: "Matte", description: "Reduced glare, professional look", priceMultiplier: 1, isDefault: true },
    { id: "fn-gloss", label: "Gloss", description: "High-impact, vivid colors", priceMultiplier: 1, isDefault: false },
  ],
  sides: [SIDES_SINGLE, SIDES_DOUBLE],
  minDpi: 150,
  bleedMm: 6,
};

const packagingSpec: PrintSpec = {
  sizes: [
    { id: "sz-sm", label: "Small Box (4×4×4 in)", width: 4, height: 4, unit: "in", priceMultiplier: 1, isDefault: true },
    { id: "sz-md", label: "Medium Box (6×6×6 in)", width: 6, height: 6, unit: "in", priceMultiplier: 1.5, isDefault: false },
    { id: "sz-lg", label: "Large Box (12×10×4 in)", width: 12, height: 10, unit: "in", priceMultiplier: 2.2, isDefault: false },
  ],
  papers: [
    { id: "pp-eco", label: "Eco Kraft", weight: "350gsm", description: "Sustainable, natural brown kraft", priceMultiplier: 1, isDefault: true },
    { id: "pp-white", label: "White SBS Board", weight: "350gsm", description: "Premium white coated board", priceMultiplier: 1.2, isDefault: false },
    { id: "pp-rigid", label: "Rigid Setup Box", weight: "2mm", description: "Luxury rigid box material", priceMultiplier: 1.8, isDefault: false },
  ],
  finishes: [
    { id: "fn-matte", label: "Matte Laminate", description: "Refined, tactile finish", priceMultiplier: 1.1, isDefault: true },
    { id: "fn-gloss", label: "Gloss Laminate", description: "Bold, striking appearance", priceMultiplier: 1.1, isDefault: false },
    { id: "fn-uv", label: "Spot UV", description: "Premium selective gloss", priceMultiplier: 1.3, isDefault: false },
    { id: "fn-foil", label: "Foil Stamp", description: "Luxury metallic accents", priceMultiplier: 1.5, isDefault: false },
  ],
  sides: [{ ...SIDES_SINGLE, isDefault: true }],
  minDpi: 300,
  bleedMm: 3,
};

const brochureSpec: PrintSpec = {
  sizes: [
    { id: "sz-a4-tri", label: 'A4 Tri-Fold (8.27" × 11.69")', width: 8.27, height: 11.69, unit: "in", priceMultiplier: 1, isDefault: true },
    { id: "sz-a4-bi", label: 'A4 Bi-Fold (8.27" × 11.69")', width: 8.27, height: 11.69, unit: "in", priceMultiplier: 1, isDefault: false },
    { id: "sz-dl-fold", label: 'DL Tri-Fold (3.9" × 8.27")', width: 3.9, height: 8.27, unit: "in", priceMultiplier: 0.85, isDefault: false },
  ],
  papers: [
    { id: "pp-130gsm", label: "130gsm Silk", weight: "130gsm", description: "Quality, vibrant colour", priceMultiplier: 1, isDefault: true },
    { id: "pp-170gsm", label: "170gsm Silk", weight: "170gsm", description: "Heavier, more premium", priceMultiplier: 1.2, isDefault: false },
    { id: "pp-250gsm", label: "250gsm Silk", weight: "250gsm", description: "Very thick, luxurious", priceMultiplier: 1.45, isDefault: false },
  ],
  finishes: [
    { id: "fn-matte", label: "Matte Laminate", description: "Smooth, anti-fingerprint", priceMultiplier: 1.1, isDefault: true },
    { id: "fn-gloss", label: "Gloss Laminate", description: "Vibrant, high-shine", priceMultiplier: 1.1, isDefault: false },
    { id: "fn-soft", label: "Soft-Touch Laminate", description: "Velvet-like premium feel", priceMultiplier: 1.25, isDefault: false },
  ],
  sides: [{ ...SIDES_DOUBLE, isDefault: true }],
  minDpi: 300,
  bleedMm: 3,
};

const merchSpec: PrintSpec = {
  sizes: [
    { id: "sz-sm", label: "Small (S)", width: 0, height: 0, unit: "in", priceMultiplier: 1, isDefault: false },
    { id: "sz-md", label: "Medium (M)", width: 0, height: 0, unit: "in", priceMultiplier: 1, isDefault: true },
    { id: "sz-lg", label: "Large (L)", width: 0, height: 0, unit: "in", priceMultiplier: 1.05, isDefault: false },
    { id: "sz-xl", label: "Extra Large (XL)", width: 0, height: 0, unit: "in", priceMultiplier: 1.1, isDefault: false },
  ],
  papers: [
    { id: "pp-100cotton", label: "100% Cotton", weight: "180gsm", description: "Soft, breathable, natural", priceMultiplier: 1, isDefault: true },
    { id: "pp-polycotton", label: "Poly-Cotton Blend", weight: "200gsm", description: "Durable, colour-fast", priceMultiplier: 1.1, isDefault: false },
    { id: "pp-performance", label: "Performance Polyester", weight: "160gsm", description: "Moisture-wicking, athletic", priceMultiplier: 1.15, isDefault: false },
  ],
  finishes: [
    { id: "fn-dtg", label: "DTG Print", description: "Direct-to-garment, full colour", priceMultiplier: 1, isDefault: true },
    { id: "fn-screen", label: "Screen Print", description: "Classic, durable ink", priceMultiplier: 0.9, isDefault: false },
    { id: "fn-embroidery", label: "Embroidery", description: "Premium raised texture", priceMultiplier: 1.4, isDefault: false },
  ],
  sides: [SIDES_SINGLE, SIDES_DOUBLE],
  minDpi: 300,
  bleedMm: 0,
};

// ─── Template fields ──────────────────────────────────────────────────────────

const businessCardTemplateFields: TemplateField[] = [
  { id: "full_name", label: "Full Name", type: "text", placeholder: "e.g. Arjun Sharma", required: true, maxLength: 60 },
  { id: "job_title", label: "Job Title", type: "text", placeholder: "e.g. Marketing Manager", required: false, maxLength: 80 },
  { id: "company", label: "Company", type: "text", placeholder: "e.g. Urgent Printers", required: false, maxLength: 80 },
  { id: "phone", label: "Phone", type: "phone", placeholder: "e.g. +91 98765 43210", required: true, maxLength: 20 },
  { id: "email", label: "Email", type: "email", placeholder: "e.g. arjun@company.com", required: true, maxLength: 120 },
  { id: "website", label: "Website", type: "url", placeholder: "e.g. www.company.com", required: false, maxLength: 120 },
  { id: "address", label: "Address", type: "multiline", placeholder: "Business address (optional)", required: false, maxLength: 200 },
];

// ─── Products ─────────────────────────────────────────────────────────────────

export const mockProducts: Product[] = [
  // ── Business Cards ──────────────────────────────────────────────────────────
  {
    id: "prod-bc-1",
    slug: "standard-business-cards",
    name: "Standard Business Cards",
    categoryId: "cat-1",
    categorySlug: "business-cards",
    categoryName: "Business Cards",
    description: "Our most popular business card. Printed on premium 14pt cardstock with sharp colour reproduction. Ideal for professionals who want a reliable, polished first impression. Choose matte for understated elegance or gloss to make colours pop.",
    shortDescription: "Premium 14pt business cards with sharp colour reproduction.",
    images: [
      "https://picsum.photos/seed/bc1a/800/600",
      "https://picsum.photos/seed/bc1b/800/600",
      "https://picsum.photos/seed/bc1c/800/600",
    ],
    printSpec: businessCardSpec,
    pricingTiers: makeTiers(4.00, [50, 100, 250, 500, 750, 1000]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.8,
    reviewCount: 142,
    isFeatured: true,
    tags: ["bestseller", "professional", "networking"],
    badge: "sale",
    customizationMode: "template" as CustomizationMode,
    templateFields: businessCardTemplateFields,
  },
  {
    id: "prod-bc-2",
    slug: "luxury-foil-business-cards",
    name: "Luxury Foil Business Cards",
    categoryId: "cat-1",
    categorySlug: "business-cards",
    categoryName: "Business Cards",
    description: "Stand out from the crowd with stunning metallic foil accents on 32pt ultra-thick cardstock. These cards command attention and communicate premium quality before you say a word. Perfect for executives, luxury brands, and creative professionals.",
    shortDescription: "32pt ultra-thick cards with metallic foil accents.",
    images: [
      "https://picsum.photos/seed/bc2a/800/600",
      "https://picsum.photos/seed/bc2b/800/600",
      "https://picsum.photos/seed/bc2c/800/600",
    ],
    printSpec: { ...businessCardSpec, finishes: businessCardSpec.finishes.filter(f => ["fn-foil", "fn-uv"].includes(f.id)) },
    pricingTiers: makeTiers(14.00, [50, 100, 250, 500, 750, 1000]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.9,
    reviewCount: 87,
    isFeatured: true,
    tags: ["luxury", "premium", "foil", "executive"],
    customizationMode: "template" as CustomizationMode,
    templateFields: businessCardTemplateFields,
  },
  {
    id: "prod-bc-3",
    slug: "spot-uv-business-cards",
    name: "Spot UV Business Cards",
    categoryId: "cat-1",
    categorySlug: "business-cards",
    categoryName: "Business Cards",
    description: "Combine a smooth matte base with selective high-gloss UV coating for a tactile, eye-catching contrast. The raised, shiny elements draw the eye to your most important information — logo, name, or tagline.",
    shortDescription: "Matte base with selective gloss UV highlights.",
    images: [
      "https://picsum.photos/seed/bc3a/800/600",
      "https://picsum.photos/seed/bc3b/800/600",
      "https://picsum.photos/seed/bc3c/800/600",
    ],
    printSpec: { ...businessCardSpec, finishes: businessCardSpec.finishes.filter(f => ["fn-uv", "fn-matte"].includes(f.id)) },
    pricingTiers: makeTiers(9.00, [50, 100, 250, 500, 750, 1000]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.7,
    reviewCount: 63,
    isFeatured: false,
    tags: ["spot-uv", "luxury", "contrast"],
    customizationMode: "template" as CustomizationMode,
    templateFields: businessCardTemplateFields,
  },

  // ── Flyers ─────────────────────────────────────────────────────────────────
  {
    id: "prod-fl-1",
    slug: "a5-promotional-flyers",
    name: "A5 Promotional Flyers",
    categoryId: "cat-2",
    categorySlug: "flyers",
    categoryName: "Flyers",
    description: "Versatile A5 flyers perfect for promotions, menus, event announcements, and handouts. Printed full-colour on quality silk-coated stock with optional laminate finish for extra durability.",
    shortDescription: "Full-colour A5 flyers on quality silk stock.",
    images: [
      "https://picsum.photos/seed/fl1a/800/600",
      "https://picsum.photos/seed/fl1b/800/600",
      "https://picsum.photos/seed/fl1c/800/600",
    ],
    printSpec: flyerSpec,
    pricingTiers: makeTiers(2.00, [100, 250, 500, 1000, 2500, 5000]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.6,
    reviewCount: 98,
    isFeatured: true,
    tags: ["promotion", "event", "handout", "bestseller"],
    badge: "sale",
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },
  {
    id: "prod-fl-2",
    slug: "a4-full-colour-flyers",
    name: "A4 Full-Colour Flyers",
    categoryId: "cat-2",
    categorySlug: "flyers",
    categoryName: "Flyers",
    description: "Full A4 size gives you maximum space for your message. Perfect for menus, property listings, product catalogues, and event programmes. Double-sided printing available for even more content.",
    shortDescription: "Maximum impact A4 flyers, single or double-sided.",
    images: [
      "https://picsum.photos/seed/fl2a/800/600",
      "https://picsum.photos/seed/fl2b/800/600",
      "https://picsum.photos/seed/fl2c/800/600",
    ],
    printSpec: flyerSpec,
    pricingTiers: makeTiers(3.00, [100, 250, 500, 1000, 2500, 5000]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.5,
    reviewCount: 74,
    isFeatured: false,
    tags: ["full-page", "menu", "catalogue"],
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },
  {
    id: "prod-fl-3",
    slug: "dl-leaflets",
    name: "DL Leaflets",
    categoryId: "cat-2",
    categorySlug: "flyers",
    categoryName: "Flyers",
    description: "DL format fits perfectly in standard envelopes and leaflet racks. Ideal for direct mail campaigns, restaurant menus, and information leaflets. The slim profile ensures recipients actually read the content.",
    shortDescription: "Slim DL leaflets, perfect for direct mail and racks.",
    images: [
      "https://picsum.photos/seed/fl3a/800/600",
      "https://picsum.photos/seed/fl3b/800/600",
      "https://picsum.photos/seed/fl3c/800/600",
    ],
    printSpec: flyerSpec,
    pricingTiers: makeTiers(1.50, [100, 250, 500, 1000, 2500, 5000]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.4,
    reviewCount: 51,
    isFeatured: false,
    tags: ["direct-mail", "slim", "leaflet"],
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },

  // ── Banners ────────────────────────────────────────────────────────────────
  {
    id: "prod-bn-1",
    slug: "vinyl-outdoor-banner",
    name: "Vinyl Outdoor Banner",
    categoryId: "cat-3",
    categorySlug: "banners",
    categoryName: "Banners",
    description: "Heavy-duty 13oz vinyl banner built to withstand outdoor conditions. UV-resistant inks ensure vivid colour that lasts months. Hemmed edges and grommets included for easy hanging. Ideal for storefronts, events, and trade shows.",
    shortDescription: "Heavy-duty outdoor vinyl banner with grommets.",
    images: [
      "https://picsum.photos/seed/bn1a/800/600",
      "https://picsum.photos/seed/bn1b/800/600",
      "https://picsum.photos/seed/bn1c/800/600",
    ],
    printSpec: bannerSpec,
    pricingTiers: makeTiers(350.00, [1, 2, 5, 10, 25, 50]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.7,
    reviewCount: 118,
    isFeatured: true,
    tags: ["outdoor", "event", "storefront", "bestseller"],
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },
  {
    id: "prod-bn-2",
    slug: "retractable-banner-stand",
    name: "Retractable Banner Stand",
    categoryId: "cat-3",
    categorySlug: "banners",
    categoryName: "Banners",
    description: "Professional pull-up banner with durable aluminium stand. Sets up in seconds for trade shows, retail displays, and presentations. Includes carry bag for easy transport. Replacement graphics available.",
    shortDescription: "Pull-up banner with aluminium stand and carry bag.",
    images: [
      "https://picsum.photos/seed/bn2a/800/600",
      "https://picsum.photos/seed/bn2b/800/600",
      "https://picsum.photos/seed/bn2c/800/600",
    ],
    printSpec: {
      ...bannerSpec,
      sizes: [
        { id: "sz-33x80", label: '33" × 80" (Standard)', width: 33, height: 80, unit: "in", priceMultiplier: 1, isDefault: true },
        { id: "sz-47x80", label: '47" × 80" (Wide)', width: 47, height: 80, unit: "in", priceMultiplier: 1.3, isDefault: false },
      ],
    },
    pricingTiers: makeTiers(1400.00, [1, 2, 5, 10, 25, 50]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.8,
    reviewCount: 92,
    isFeatured: false,
    tags: ["trade-show", "retractable", "professional"],
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },
  {
    id: "prod-bn-3",
    slug: "fabric-event-banner",
    name: "Fabric Event Banner",
    categoryId: "cat-3",
    categorySlug: "banners",
    categoryName: "Banners",
    description: "Premium polyester fabric banners for an upscale look at events, retail spaces, and exhibitions. Wrinkle-resistant fabric ensures crisp presentation. Washable and reusable. Available with hanging rod or display stand.",
    shortDescription: "Wrinkle-resistant fabric banner for premium presentations.",
    images: [
      "https://picsum.photos/seed/bn3a/800/600",
      "https://picsum.photos/seed/bn3b/800/600",
      "https://picsum.photos/seed/bn3c/800/600",
    ],
    printSpec: { ...bannerSpec, papers: bannerSpec.papers.filter(p => p.id === "pp-fabric") },
    pricingTiers: makeTiers(550.00, [1, 2, 5, 10, 25, 50]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.6,
    reviewCount: 44,
    isFeatured: false,
    tags: ["fabric", "premium", "exhibition", "reusable"],
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },

  // ── Packaging ─────────────────────────────────────────────────────────────
  {
    id: "prod-pk-1",
    slug: "custom-product-boxes",
    name: "Custom Product Boxes",
    categoryId: "cat-4",
    categorySlug: "packaging",
    categoryName: "Packaging",
    description: "Fully custom printed product boxes on premium 350gsm board. Full-colour exterior printing with optional interior lining. Structural design ensures your products arrive safely while making an unforgettable unboxing experience.",
    shortDescription: "Custom printed product boxes with full-colour exterior.",
    images: [
      "https://picsum.photos/seed/pk1a/800/600",
      "https://picsum.photos/seed/pk1b/800/600",
      "https://picsum.photos/seed/pk1c/800/600",
    ],
    printSpec: packagingSpec,
    pricingTiers: makeTiers(55.00, [25, 50, 100, 250, 500, 1000]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.7,
    reviewCount: 76,
    isFeatured: true,
    tags: ["unboxing", "ecommerce", "retail", "custom"],
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },
  {
    id: "prod-pk-2",
    slug: "mailer-boxes",
    name: "Custom Mailer Boxes",
    categoryId: "cat-4",
    categorySlug: "packaging",
    categoryName: "Packaging",
    description: "Rigid mailer boxes designed for e-commerce shipping. Corrugated outer wall protects contents during transit while the printed outer surface delivers on-brand impact. Self-locking design — no tape required.",
    shortDescription: "Self-locking mailer boxes for e-commerce shipping.",
    images: [
      "https://picsum.photos/seed/pk2a/800/600",
      "https://picsum.photos/seed/pk2b/800/600",
      "https://picsum.photos/seed/pk2c/800/600",
    ],
    printSpec: packagingSpec,
    pricingTiers: makeTiers(85.00, [25, 50, 100, 250, 500, 1000]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.8,
    reviewCount: 103,
    isFeatured: false,
    tags: ["ecommerce", "shipping", "mailer", "bestseller"],
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },
  {
    id: "prod-pk-3",
    slug: "eco-kraft-packaging",
    name: "Eco Kraft Packaging",
    categoryId: "cat-4",
    categorySlug: "packaging",
    categoryName: "Packaging",
    description: "Sustainable kraft packaging for eco-conscious brands. Made from 100% recycled materials with soy-based inks. Natural brown kraft look with full-colour print available. Perfect for artisan, food, and lifestyle brands.",
    shortDescription: "Sustainable kraft packaging from recycled materials.",
    images: [
      "https://picsum.photos/seed/pk3a/800/600",
      "https://picsum.photos/seed/pk3b/800/600",
      "https://picsum.photos/seed/pk3c/800/600",
    ],
    printSpec: { ...packagingSpec, papers: packagingSpec.papers.filter(p => p.id === "pp-eco") },
    pricingTiers: makeTiers(45.00, [25, 50, 100, 250, 500, 1000]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.5,
    reviewCount: 58,
    isFeatured: false,
    tags: ["eco", "sustainable", "kraft", "artisan"],
    badge: "sale",
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },

  // ── Brochures ─────────────────────────────────────────────────────────────
  {
    id: "prod-br-1",
    slug: "a4-tri-fold-brochure",
    name: "A4 Tri-Fold Brochure",
    categoryId: "cat-5",
    categorySlug: "brochures",
    categoryName: "Brochures",
    description: "The classic tri-fold brochure divides your A4 sheet into six panels of content. Perfect for introducing your business, showcasing services, or explaining a product. Scores precisely for clean, professional folding.",
    shortDescription: "Classic tri-fold A4 brochure with six content panels.",
    images: [
      "https://picsum.photos/seed/br1a/800/600",
      "https://picsum.photos/seed/br1b/800/600",
      "https://picsum.photos/seed/br1c/800/600",
    ],
    printSpec: brochureSpec,
    pricingTiers: makeTiers(6.00, [50, 100, 250, 500, 1000, 2500]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.6,
    reviewCount: 82,
    isFeatured: true,
    tags: ["trifold", "corporate", "informational", "bestseller"],
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },
  {
    id: "prod-br-2",
    slug: "a4-bi-fold-brochure",
    name: "A4 Bi-Fold Brochure",
    categoryId: "cat-5",
    categorySlug: "brochures",
    categoryName: "Brochures",
    description: "A bi-fold brochure creates four panels with a premium, booklet-like feel. More space per panel means larger images and more detailed content. Ideal for property details, annual reports, and menu booklets.",
    shortDescription: "Booklet-style bi-fold with four spacious content panels.",
    images: [
      "https://picsum.photos/seed/br2a/800/600",
      "https://picsum.photos/seed/br2b/800/600",
      "https://picsum.photos/seed/br2c/800/600",
    ],
    printSpec: brochureSpec,
    pricingTiers: makeTiers(8.00, [50, 100, 250, 500, 1000, 2500]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.5,
    reviewCount: 61,
    isFeatured: false,
    tags: ["bifold", "property", "menu", "booklet"],
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },
  {
    id: "prod-br-3",
    slug: "soft-touch-luxury-brochure",
    name: "Soft-Touch Luxury Brochure",
    categoryId: "cat-5",
    categorySlug: "brochures",
    categoryName: "Brochures",
    description: "Elevate your brand materials with our exclusive soft-touch laminate finish. The velvety texture is instantly memorable and positions your business at the premium end. Printed on heavy 250gsm stock for maximum prestige.",
    shortDescription: "Velvety soft-touch laminate on heavy 250gsm stock.",
    images: [
      "https://picsum.photos/seed/br3a/800/600",
      "https://picsum.photos/seed/br3b/800/600",
      "https://picsum.photos/seed/br3c/800/600",
    ],
    printSpec: { ...brochureSpec, finishes: brochureSpec.finishes.filter(f => f.id === "fn-soft"), papers: brochureSpec.papers.filter(p => p.id === "pp-250gsm") },
    pricingTiers: makeTiers(14.00, [50, 100, 250, 500, 1000, 2500]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.9,
    reviewCount: 38,
    isFeatured: false,
    tags: ["luxury", "soft-touch", "premium", "prestige"],
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },

  // ── Custom Merch ──────────────────────────────────────────────────────────
  {
    id: "prod-mc-1",
    slug: "custom-printed-t-shirts",
    name: "Custom Printed T-Shirts",
    categoryId: "cat-6",
    categorySlug: "custom-merch",
    categoryName: "Custom Merch",
    description: "High-quality 100% cotton T-shirts with full-colour DTG or screen printing. Perfect for team uniforms, event merchandise, brand giveaways, and promotional campaigns. Pre-washed for minimal shrinkage.",
    shortDescription: "Full-colour custom printed T-shirts on premium cotton.",
    images: [
      "https://picsum.photos/seed/mc1a/800/600",
      "https://picsum.photos/seed/mc1b/800/600",
      "https://picsum.photos/seed/mc1c/800/600",
    ],
    printSpec: merchSpec,
    pricingTiers: makeTiers(220.00, [10, 25, 50, 100, 250, 500]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.7,
    reviewCount: 134,
    isFeatured: true,
    tags: ["apparel", "event", "team", "bestseller"],
    badge: "sale",
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },
  {
    id: "prod-mc-2",
    slug: "branded-tote-bags",
    name: "Branded Tote Bags",
    categoryId: "cat-6",
    categorySlug: "custom-merch",
    categoryName: "Custom Merch",
    description: "Eco-friendly heavyweight cotton tote bags with full-colour print or embroidery. The daily-use item that gives your brand constant exposure. Gusset base for a generous capacity. Available in natural, black, and navy.",
    shortDescription: "Eco cotton tote bags with full-colour print or embroidery.",
    images: [
      "https://picsum.photos/seed/mc2a/800/600",
      "https://picsum.photos/seed/mc2b/800/600",
      "https://picsum.photos/seed/mc2c/800/600",
    ],
    printSpec: { ...merchSpec, sizes: [{ id: "sz-std", label: "Standard (38×42cm)", width: 38, height: 42, unit: "cm", priceMultiplier: 1, isDefault: true }] },
    pricingTiers: makeTiers(110.00, [10, 25, 50, 100, 250, 500]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.6,
    reviewCount: 89,
    isFeatured: false,
    tags: ["eco", "tote", "everyday", "promotion"],
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },
  {
    id: "prod-mc-3",
    slug: "embroidered-caps",
    name: "Embroidered Caps",
    categoryId: "cat-6",
    categorySlug: "custom-merch",
    categoryName: "Custom Merch",
    description: "Classic structured caps with premium embroidery. Embroidery gives a high-end, durable result that holds up wash after wash. 6-panel construction with adjustable strap. Great for hospitality, sports teams, and brand ambassador programmes.",
    shortDescription: "Premium embroidered caps with durable 6-panel construction.",
    images: [
      "https://picsum.photos/seed/mc3a/800/600",
      "https://picsum.photos/seed/mc3b/800/600",
      "https://picsum.photos/seed/mc3c/800/600",
    ],
    printSpec: { ...merchSpec, sizes: [{ id: "sz-onesize", label: "One Size (adjustable)", width: 0, height: 0, unit: "in", priceMultiplier: 1, isDefault: true }], finishes: [{ id: "fn-embroidery", label: "Embroidery", description: "Premium raised texture", priceMultiplier: 1.4, isDefault: true }] },
    pricingTiers: makeTiers(180.00, [10, 25, 50, 100, 250, 500]),
    turnaroundOptions: standardTurnaround,
    averageRating: 4.8,
    reviewCount: 57,
    isFeatured: false,
    tags: ["caps", "embroidery", "sports", "corporate"],
    customizationMode: "artwork" as CustomizationMode,
    templateFields: [],
  },
];
