import type { Review } from "@/types";

export const mockReviews: Review[] = [
  // ── Standard Business Cards ───────────────────────────────────────────────
  {
    id: "rev-bc1-1",
    productId: "prod-bc-1",
    userId: "user-101",
    authorName: "Sarah Mitchell",
    authorAvatarUrl: "https://picsum.photos/seed/ava1/100/100",
    rating: 5,
    title: "Exactly what I needed for my new business",
    body: "The print quality blew me away. Colours matched my design perfectly and the cardstock feels premium without being over the top. Arrived in 4 days — faster than promised. Ordered 250 and will definitely be back for more.",
    verifiedPurchase: true,
    helpfulCount: 23,
    createdAt: "2025-11-12T09:14:00Z",
  },
  {
    id: "rev-bc1-2",
    productId: "prod-bc-1",
    userId: "user-102",
    authorName: "James Okafor",
    authorAvatarUrl: "https://picsum.photos/seed/ava2/100/100",
    rating: 4,
    title: "Great quality, slightly slow delivery",
    body: "Cards look brilliant and feel solid. Went with the matte finish and it gives a really professional look. Only docking a star because delivery took 7 days when I was hoping for 5. Would still recommend.",
    verifiedPurchase: true,
    helpfulCount: 11,
    createdAt: "2025-10-28T14:32:00Z",
  },
  {
    id: "rev-bc1-3",
    productId: "prod-bc-1",
    userId: "user-103",
    authorName: "Priya Nair",
    authorAvatarUrl: "https://picsum.photos/seed/ava3/100/100",
    rating: 5,
    title: "Handed them out at a conference — huge compliments",
    body: "Everyone at the event asked where I got these cards printed. The 14pt cardstock strikes the perfect balance between premium and affordable. Uploaded my Canva design and it came out perfectly. Five stars without hesitation.",
    verifiedPurchase: true,
    helpfulCount: 34,
    createdAt: "2025-10-05T11:20:00Z",
  },

  // ── Luxury Foil Business Cards ────────────────────────────────────────────
  {
    id: "rev-bc2-1",
    productId: "prod-bc-2",
    userId: "user-104",
    authorName: "Alexandra Chen",
    authorAvatarUrl: "https://picsum.photos/seed/ava4/100/100",
    rating: 5,
    title: "Worth every penny — absolutely stunning",
    body: "These are the most luxurious business cards I have ever seen, let alone owned. The gold foil on my logo catches the light beautifully. The 32pt thickness means they have genuine heft. Clients always comment on them.",
    verifiedPurchase: true,
    helpfulCount: 41,
    createdAt: "2025-11-20T16:45:00Z",
  },
  {
    id: "rev-bc2-2",
    productId: "prod-bc-2",
    userId: "user-105",
    authorName: "Marcus Williams",
    authorAvatarUrl: "https://picsum.photos/seed/ava5/100/100",
    rating: 5,
    title: "Premium cards that represent my brand perfectly",
    body: "As a luxury consultant, my cards need to reflect the quality I promise clients. These foil cards do exactly that. The foil registration is precise and the stock is genuinely thick. Worth the price premium.",
    verifiedPurchase: true,
    helpfulCount: 28,
    createdAt: "2025-10-14T10:08:00Z",
  },
  {
    id: "rev-bc2-3",
    productId: "prod-bc-2",
    userId: "user-106",
    authorName: "Tomoko Ishida",
    authorAvatarUrl: "https://picsum.photos/seed/ava6/100/100",
    rating: 4,
    title: "Stunning results but turnaround is longer",
    body: "The finished cards are truly beautiful — the silver foil on dark navy is striking. My only note is that the foil cards took 8 business days on standard turnaround. If you're time-sensitive, choose the rush option.",
    verifiedPurchase: true,
    helpfulCount: 15,
    createdAt: "2025-09-22T13:55:00Z",
  },

  // ── Spot UV Business Cards ────────────────────────────────────────────────
  {
    id: "rev-bc3-1",
    productId: "prod-bc-3",
    userId: "user-107",
    authorName: "Daniel Foster",
    authorAvatarUrl: "https://picsum.photos/seed/ava7/100/100",
    rating: 5,
    title: "The tactile contrast is incredible",
    body: "Running your finger across these cards and feeling the raised UV elements is a genuinely satisfying experience. The matte base vs gloss logo contrast looks ultra-professional. Ordered 100 for a networking event and got so many compliments.",
    verifiedPurchase: true,
    helpfulCount: 19,
    createdAt: "2025-11-01T08:30:00Z",
  },
  {
    id: "rev-bc3-2",
    productId: "prod-bc-3",
    userId: "user-108",
    authorName: "Rhiannon Davies",
    authorAvatarUrl: "https://picsum.photos/seed/ava8/100/100",
    rating: 4,
    title: "Great effect, make sure your file is perfect",
    body: "The spot UV effect is genuinely impressive. Do make sure your artwork is exactly right before submitting though — the UV layer precisely matches what you provide, so any imperfection shows. Customer service was helpful when I had a question.",
    verifiedPurchase: true,
    helpfulCount: 22,
    createdAt: "2025-10-19T15:15:00Z",
  },
  {
    id: "rev-bc3-3",
    productId: "prod-bc-3",
    userId: "user-109",
    authorName: "Leon Baptiste",
    authorAvatarUrl: "https://picsum.photos/seed/ava9/100/100",
    rating: 5,
    title: "My most complimented business cards ever",
    body: "Switched from plain matte cards to these spot UV ones and have never looked back. The contrast is subtle enough to look sophisticated but noticeable enough to generate conversation. Excellent quality control — every single card is perfect.",
    verifiedPurchase: true,
    helpfulCount: 17,
    createdAt: "2025-09-30T12:00:00Z",
  },

  // ── A5 Promotional Flyers ─────────────────────────────────────────────────
  {
    id: "rev-fl1-1",
    productId: "prod-fl-1",
    userId: "user-110",
    authorName: "Stephanie Walsh",
    authorAvatarUrl: "https://picsum.photos/seed/ava10/100/100",
    rating: 5,
    title: "Brilliant for our restaurant promotions",
    body: "We use these for our monthly specials and the colour reproduction is consistently excellent. The gloss laminate option makes food photography look mouth-watering. Fast turnaround every time — will keep reordering.",
    verifiedPurchase: true,
    helpfulCount: 31,
    createdAt: "2025-11-08T09:45:00Z",
  },
  {
    id: "rev-fl1-2",
    productId: "prod-fl-1",
    userId: "user-111",
    authorName: "Ahmed Khalil",
    authorAvatarUrl: "https://picsum.photos/seed/ava11/100/100",
    rating: 4,
    title: "Good quality, exactly as expected",
    body: "Ordered 500 for a charity event and they arrived well-packaged and looking great. The 130gsm silk stock has a good weight to it. Colour accuracy was spot-on with my proof. Would order again.",
    verifiedPurchase: true,
    helpfulCount: 14,
    createdAt: "2025-10-22T14:00:00Z",
  },
  {
    id: "rev-fl1-3",
    productId: "prod-fl-1",
    userId: "user-112",
    authorName: "Caitlin Hughes",
    authorAvatarUrl: "https://picsum.photos/seed/ava12/100/100",
    rating: 5,
    title: "Fast, affordable, and excellent quality",
    body: "As a freelance graphic designer, I recommend Urgent Printers to all my clients. The A5 flyers are the most popular product — consistent quality, competitive pricing, and delivery always arrives when promised.",
    verifiedPurchase: true,
    helpfulCount: 38,
    createdAt: "2025-10-10T11:30:00Z",
  },

  // ── Vinyl Outdoor Banner ──────────────────────────────────────────────────
  {
    id: "rev-bn1-1",
    productId: "prod-bn-1",
    userId: "user-113",
    authorName: "Robert Jansen",
    authorAvatarUrl: "https://picsum.photos/seed/ava13/100/100",
    rating: 5,
    title: "Survived a full outdoor event season",
    body: "Our 3×6 banner has now been used at six outdoor events, three of which had significant wind and rain. It looks as good as the day it arrived. The grommets are solid and the inks haven't faded at all. Exceptional durability.",
    verifiedPurchase: true,
    helpfulCount: 44,
    createdAt: "2025-11-15T10:20:00Z",
  },
  {
    id: "rev-bn1-2",
    productId: "prod-bn-1",
    userId: "user-114",
    authorName: "Fiona McCallum",
    authorAvatarUrl: "https://picsum.photos/seed/ava14/100/100",
    rating: 4,
    title: "Great banner, print is vibrant",
    body: "Very happy with the print quality on our 4×8 banner. Colours are bold and the text is crisp even at reading distance. Took 6 days on standard turnaround. Hemming is neat and grommets well-positioned.",
    verifiedPurchase: true,
    helpfulCount: 21,
    createdAt: "2025-10-30T13:10:00Z",
  },
  {
    id: "rev-bn1-3",
    productId: "prod-bn-1",
    userId: "user-115",
    authorName: "David Osei",
    authorAvatarUrl: "https://picsum.photos/seed/ava15/100/100",
    rating: 5,
    title: "Perfect for our gym's exterior signage",
    body: "Ordered a 5×10 banner for our gym exterior. It's been up for four months through sun, wind, and rain, and it still looks vibrant. The heavy 18oz vinyl was the right choice for a permanent installation. Huge compliments from members.",
    verifiedPurchase: true,
    helpfulCount: 29,
    createdAt: "2025-09-18T16:00:00Z",
  },

  // ── Custom Product Boxes ──────────────────────────────────────────────────
  {
    id: "rev-pk1-1",
    productId: "prod-pk-1",
    userId: "user-116",
    authorName: "Isabella Rossi",
    authorAvatarUrl: "https://picsum.photos/seed/ava16/100/100",
    rating: 5,
    title: "Our customers love the unboxing experience",
    body: "Since switching to these custom boxes, our product reviews are full of comments about the packaging. The matte laminate with spot UV logo looks incredibly premium. Structural quality is excellent — no crushed corners in transit.",
    verifiedPurchase: true,
    helpfulCount: 52,
    createdAt: "2025-11-18T09:00:00Z",
  },
  {
    id: "rev-pk1-2",
    productId: "prod-pk-1",
    userId: "user-117",
    authorName: "Oliver Thompson",
    authorAvatarUrl: "https://picsum.photos/seed/ava17/100/100",
    rating: 5,
    title: "Elevated our brand perception overnight",
    body: "We used to ship in plain brown boxes. Switching to custom printed boxes was the single best decision for our brand this year. Response from customers has been incredible. Print quality is consistently high across multiple orders.",
    verifiedPurchase: true,
    helpfulCount: 37,
    createdAt: "2025-10-25T11:45:00Z",
  },
  {
    id: "rev-pk1-3",
    productId: "prod-pk-1",
    userId: "user-118",
    authorName: "Yuki Tanaka",
    authorAvatarUrl: "https://picsum.photos/seed/ava18/100/100",
    rating: 4,
    title: "High quality, slightly long lead time",
    body: "The boxes themselves are excellent — rigid, well-printed, and the foil stamp on our logo looks premium. Allow extra time as custom packaging takes longer than standard products. Worth the wait, but plan ahead.",
    verifiedPurchase: true,
    helpfulCount: 18,
    createdAt: "2025-10-08T14:30:00Z",
  },

  // ── A4 Tri-Fold Brochure ──────────────────────────────────────────────────
  {
    id: "rev-br1-1",
    productId: "prod-br-1",
    userId: "user-119",
    authorName: "Hannah Scott",
    authorAvatarUrl: "https://picsum.photos/seed/ava19/100/100",
    rating: 5,
    title: "Polished brochures for our property listings",
    body: "Estate agency needs high-quality print materials and these brochures deliver. The 170gsm silk with gloss laminate makes our property photos look stunning. Fold lines are perfectly scored — no cracking. Reordering regularly.",
    verifiedPurchase: true,
    helpfulCount: 26,
    createdAt: "2025-11-05T10:15:00Z",
  },
  {
    id: "rev-br1-2",
    productId: "prod-br-1",
    userId: "user-120",
    authorName: "Michael Torres",
    authorAvatarUrl: "https://picsum.photos/seed/ava20/100/100",
    rating: 4,
    title: "Great value for the quality",
    body: "Ordered 250 for a trade show. Very happy with the result — print quality is sharp, colours are accurate, and the folds are clean. Knocked one star only because the proof approval took a day longer than I expected.",
    verifiedPurchase: true,
    helpfulCount: 13,
    createdAt: "2025-10-17T12:40:00Z",
  },
  {
    id: "rev-br1-3",
    productId: "prod-br-1",
    userId: "user-121",
    authorName: "Amara Diallo",
    authorAvatarUrl: "https://picsum.photos/seed/ava21/100/100",
    rating: 5,
    title: "My go-to for all client presentations",
    body: "I design and print brochures for multiple clients. Urgent Printers has become my default for quality and reliability. The tri-fold brochures are consistently excellent — the matte laminate finish on the soft-touch stock is particularly impressive.",
    verifiedPurchase: true,
    helpfulCount: 33,
    createdAt: "2025-09-28T09:50:00Z",
  },

  // ── Custom Printed T-Shirts ───────────────────────────────────────────────
  {
    id: "rev-mc1-1",
    productId: "prod-mc-1",
    userId: "user-122",
    authorName: "Chris Anderson",
    authorAvatarUrl: "https://picsum.photos/seed/ava22/100/100",
    rating: 5,
    title: "Perfect team shirts for our startup",
    body: "Ordered 30 shirts for our team in various sizes and every single one came out perfectly. The DTG printing reproduces our gradient logo better than I thought possible on fabric. The cotton is genuinely soft and has held up through multiple washes.",
    verifiedPurchase: true,
    helpfulCount: 40,
    createdAt: "2025-11-10T11:00:00Z",
  },
  {
    id: "rev-mc1-2",
    productId: "prod-mc-1",
    userId: "user-123",
    authorName: "Natasha Patel",
    authorAvatarUrl: "https://picsum.photos/seed/ava23/100/100",
    rating: 4,
    title: "Excellent shirts, sizing runs slightly large",
    body: "Great quality shirts — the print is vibrant and the cotton is comfortable. Note that sizing runs about half a size large, so consider ordering down. Customer service was helpful when I asked about sizing before ordering.",
    verifiedPurchase: true,
    helpfulCount: 27,
    createdAt: "2025-10-20T15:30:00Z",
  },
  {
    id: "rev-mc1-3",
    productId: "prod-mc-1",
    userId: "user-124",
    authorName: "Brendan Kelly",
    authorAvatarUrl: "https://picsum.photos/seed/ava24/100/100",
    rating: 5,
    title: "Brilliant for our sports club",
    body: "Ordered 50 shirts for our football club. The screen printing on the dark navy base looks incredibly sharp. After a full season of washing, the print is still vivid with no peeling or cracking. Exactly what you want from team kit.",
    verifiedPurchase: true,
    helpfulCount: 35,
    createdAt: "2025-09-25T08:30:00Z",
  },
];
