export const ROUTES = {
  home: "/",
  products: "/products",
  category: (slug: string) => `/products/${slug}`,
  product: (categorySlug: string, slug: string) => `/products/${categorySlug}/${slug}`,
  cart: "/cart",
  checkout: "/checkout",
  checkoutConfirmation: (orderId: string) => `/checkout/confirmation/${orderId}`,
  login: "/auth/login",
  register: "/auth/register",
  verifyOtp: "/auth/verify",
  account: "/account",
  accountOrders: "/account/orders",
  accountOrder: (id: string) => `/account/orders/${id}`,
  accountSaved: "/account/saved",
  accountAddresses: "/account/addresses",
  accountProfile: "/account/profile",
  search: "/search",
} as const;
